# Generated by Django 5.1.4 on 2025-01-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, unique=True)),
                ('brand_logo', models.ImageField(upload_to='brand_logos/')),
                ('brand_description', models.TextField()),
                ('brand_tone', models.CharField(choices=[('formal', 'Formal'), ('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual')], default='formal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_images', models.ImageField(upload_to='product_images/')),
                ('description_about_product', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_images', models.ImageField(upload_to='post_images/')),
                ('post_caption', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.addproduct')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SchedulePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(null=True, upload_to='scheduled_post_images/')),
                ('post_caption', models.CharField(max_length=255, null=True)),
                ('post_type', models.CharField(choices=[('image_only', 'Image Only'), ('image_text', 'Image with Text')], default='image_only', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vibe', models.CharField(default='professional', max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='app.brand')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='app.addproduct')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
