# Generated by Django 5.1.4 on 2025-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepost',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
